repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.48.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.2.0
  hooks:
    - id: gitleaks
